-- BYTE BACK 2단계 학습용 자료 테이블
-- 실제 자료나 비밀값을 이 파일에 넣지 않는다.

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  owner_id uuid,
  title text not null,
  content text not null,
  created_at timestamptz not null default now()
);

alter table public.notes
  enable row level security;

-- 브라우저 역할은 DB 테이블을 직접 읽지 못한다.
revoke all on table public.notes
  from anon, authenticated;

-- Vercel 서버 함수만 서버 전용 자격으로 읽는다.
grant select on table public.notes
  to service_role;
